# config.py — все константы бота: названия, цены, апселлы, описания разборов

# ── ПРАВКА: убрали "(Полная)" из matrix_full ─────────────────────────────────
TITLES = {
    "free":           "💫 Матрица судьбы",
    "matrix_full":    "🔮 Матрица судьбы",
    "finance":        "💹 Финансовый прогноз",
    "wealth_blocks":  "🚧 Блоки богатства",
    "freedom_path":   "🗺 Путь к свободе",
    "calling":        "🌠 Призвание",
    "promotion":      "📈 Повышение",
    "own_business":   "🏢 Свой бизнес",
    "hidden_talents": "✨ Скрытые таланты",
    "main_fear":      "😨 Главный страх",
    "forecast_2026":  "🗓 Прогноз на 2026 год",
    "strong_weak":    "⚖️ Сильная и слабая сторона",
    "compat":         "💑 Совместимость двух людей",
    "when":           "💘 Когда встретишь того самого",
    "portrait":       "💍 Портрет идеального партнёра",
    "unlucky":        "💔 Почему не везёт в любви",
    "mission":        "🌟 Предназначение и миссия",
    "karma":          "🔴 Кармический долг",
    "career":         "💼 Карьерный путь",
    "money":          "💰 Денежный код",
    "days":           "🌙 Сильные и слабые дни",
    "ex":             "💔 Вернётся ли бывший",
    "cold":           "❄️ Почему он охладел",
    "toxic":          "☠️ Токсичная или кармическая связь",
    "lonely":         "😔 Почему ты одинока",
    "breakup":        "💔 Разбор после расставания",
    "health_code":    "💚 Код здоровья",
    "energy_drain":   "⚡ Что крадёт энергию",
    "body_message":   "🫀 Послания тела",
    "stress_number":  "😤 Число стресса",
    "intuition":      "🔮 Интуиция и внутренний голос",
    "past_life":      "📜 Прошлые жизни",
    "future_portal":  "🌟 Прогноз на 3 года",
    "turning_point":  "🔄 Поворотные точки судьбы",
    "ancestor_code":  "🌳 Родовой код",
}

PRICES = {
    "matrix_full":   149,
    "forecast_2026": 149,
    "wealth_blocks": 149,
    "freedom_path":  149,
    "mission":       99,
    "karma":         99,
    "compat":        99,
    "own_business":  99,
    "finance":       99,
    "promotion":     99,
    "calling":       79,
    "career":        79,
    "money":         79,
    "when":          79,
    "portrait":      79,
    "breakup":       79,
    "toxic":         79,
    "hidden_talents":79,
    "days":          79,
    "unlucky":       49,
    "ex":            49,
    "cold":          49,
    "lonely":        49,
    "main_fear":     49,
    "strong_weak":   49,
    "health_code":   79,
    "energy_drain":  49,
    "body_message":  49,
    "stress_number": 49,
    "intuition":     79,
    "past_life":     99,
    "future_portal": 149,
    "turning_point": 79,
    "ancestor_code": 99,
}

PDF_KEYS = {k for k, v in PRICES.items() if v >= 79}

PAID_RAZBORY  = {k: v for k, v in TITLES.items() if k != "free"}
FREE_ELIGIBLE = {k for k, v in PRICES.items() if v <= 99}

UPSELLS = {
    "matrix_full":    ("forecast_2026", "mission"),
    "forecast_2026":  ("matrix_full",   "karma"),
    "finance":        ("wealth_blocks",  "freedom_path"),
    "wealth_blocks":  ("finance",        "own_business"),
    "freedom_path":   ("calling",        "own_business"),
    "calling":        ("career",         "own_business"),
    "career":         ("promotion",      "money"),
    "money":          ("finance",        "wealth_blocks"),
    "karma":          ("mission",        "matrix_full"),
    "mission":        ("karma",          "hidden_talents"),
    "hidden_talents": ("calling",        "strong_weak"),
    "promotion":      ("career",         "own_business"),
    "own_business":   ("freedom_path",   "finance"),
    "compat":         ("when",           "portrait"),
    "when":           ("portrait",       "compat"),
    "portrait":       ("when",           "unlucky"),
    "unlucky":        ("ex",             "lonely"),
    "ex":             ("toxic",          "compat"),
    "cold":           ("toxic",          "ex"),
    "toxic":          ("cold",           "breakup"),
    "lonely":         ("unlucky",        "portrait"),
    "breakup":        ("ex",             "toxic"),
    "days":           ("finance",        "forecast_2026"),
    "strong_weak":    ("hidden_talents", "main_fear"),
    "main_fear":      ("strong_weak",    "karma"),
    "health_code":    ("energy_drain",   "intuition"),
    "energy_drain":   ("health_code",    "stress_number"),
    "body_message":   ("energy_drain",   "health_code"),
    "stress_number":  ("energy_drain",   "body_message"),
    "intuition":      ("health_code",    "past_life"),
    "past_life":      ("ancestor_code",  "karma"),
    "future_portal":  ("turning_point",  "forecast_2026"),
    "turning_point":  ("future_portal",  "past_life"),
    "ancestor_code":  ("past_life",      "karma"),
}

SECTION_DESTINY = ["matrix_full", "mission", "hidden_talents", "strong_weak", "main_fear", "karma", "forecast_2026"]
SECTION_MONEY   = ["finance", "wealth_blocks", "freedom_path", "calling", "promotion", "own_business", "career", "money", "days"]
SECTION_LOVE    = ["compat", "when", "portrait", "unlucky", "ex", "cold", "toxic", "lonely", "breakup"]
SECTION_HEALTH  = ["health_code", "energy_drain", "body_message", "stress_number", "intuition"]
SECTION_PAST    = ["past_life", "future_portal", "turning_point", "ancestor_code"]

# ── ПРАВКА: описания разборов — показываются перед выбором даты ───────────────
DESCRIPTIONS = {
    "matrix_full":   "Полный разбор твоей личности — характер, таланты, денежный код, любовь, карма и прогноз на 2026 год.\n~1300 слов • PDF в подарок 📄",
    "forecast_2026": "Подробный прогноз — любовь, деньги, карьера, лучшие и осторожные периоды 2026 года.\n~1300 слов • PDF в подарок 📄",
    "wealth_blocks": "4-5 конкретных блоков которые мешают деньгам, с планом как каждый убрать.\n~1300 слов • PDF в подарок 📄",
    "freedom_path":  "Твой личный путь к финансовой свободе — через что идти, шаги и сроки.\n~1300 слов • PDF в подарок 📄",
    "mission":       "Для чего ты пришла в этот мир — конкретно и с шагами реализации.\n~1000 слов • PDF в подарок 📄",
    "karma":         "Что несёт твой кармический долг и как его закрыть в этой жизни.\n~1000 слов • PDF в подарок 📄",
    "compat":        "Сильные стороны пары, зоны конфликта, честный прогноз отношений.\n~1000 слов • PDF в подарок 📄",
    "own_business":  "Подходит ли тебе свой бизнес, в каких нишах и когда лучше стартовать.\n~1000 слов • PDF в подарок 📄",
    "finance":       "Финансовый прогноз на год — когда ждать подъём и чего избегать.\n~1000 слов • PDF в подарок 📄",
    "promotion":     "Когда и как получить повышение — лучшие периоды и стратегии.\n~1000 слов • PDF в подарок 📄",
    "calling":       "Твоё истинное призвание — конкретно и с планом перехода.\n~750 слов • PDF в подарок 📄",
    "career":        "Идеальная профессия, сильные стороны на работе, пик карьеры.\n~750 слов • PDF в подарок 📄",
    "money":         "Твой денежный код — как деньги приходят и что их блокирует.\n~750 слов • PDF в подарок 📄",
    "when":          "Когда встретишь того самого — период, обстоятельства, знаки.\n~750 слов • PDF в подарок 📄",
    "portrait":      "Числовой портрет идеального партнёра и где его искать.\n~750 слов • PDF в подарок 📄",
    "breakup":       "Почему это произошло, урок отношений и прогноз новой любви.\n~750 слов • PDF в подарок 📄",
    "toxic":         "Токсичная или кармическая — диагноз честно и план выхода.\n~750 слов • PDF в подарок 📄",
    "hidden_talents":"Скрытые таланты которые ты не замечаешь и как они приносят деньги.\n~750 слов • PDF в подарок 📄",
    "days":          "Сильные и слабые дни месяца для дел, любви и финансов.\n~750 слов • PDF в подарок 📄",
    "health_code":   "Природная конституция, уязвимые места и источники восстановления.\n~750 слов • PDF в подарок 📄",
    "intuition":     "Насколько сильна твоя интуиция и как её развить — практики для твоего числа.\n~750 слов • PDF в подарок 📄",
    "turning_point": "Поворотные точки судьбы — когда будет следующий и как его использовать.\n~750 слов • PDF в подарок 📄",
    "unlucky":       "Один главный паттерн который мешает в любви — назван прямо и с выходом.\n~400 слов",
    "ex":            "Вернётся ли бывший — прямой ответ и стоит ли возобновлять.\n~400 слов",
    "cold":          "Почему охладел и что конкретно сделать чтобы изменить ситуацию.\n~400 слов",
    "lonely":        "Откуда берётся одиночество в числах и что реально его меняет.\n~400 слов",
    "main_fear":     "Главный страх который управляет решениями — назван прямо и с планом выхода.\n~400 слов",
    "strong_weak":   "Честный разбор сильных и слабых сторон — как слабость превратить в силу.\n~400 слов",
    "energy_drain":  "Что крадёт энергию — люди, ситуации, привычки — и как восстановиться.\n~400 слов",
    "body_message":  "Что тело говорит через симптомы и как наладить с ним связь.\n~400 слов",
    "stress_number": "Как твоё число реагирует на стресс и что реально помогает именно тебе.\n~400 слов",
    "past_life":     "Прошлые жизни — кем была, что перенесла и как это влияет сейчас.\n~1000 слов • PDF в подарок 📄",
    "future_portal": "Прогноз на 3 года — 2025, 2026, 2027 — любовь, деньги, главные события.\n~1400 слов • PDF в подарок 📄",
    "ancestor_code": "Таланты и травмы рода, как они влияют и как стать звеном исцеления.\n~1000 слов • PDF в подарок 📄",
}
